services:
  # DataFixtures 服务（仅在开发环境中启用）
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # DataFixtures 自动加载
  Tourze\WechatBotBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']